name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - name: Build
      run: |
        yarn
        yarn build
        
    - name: Setup Git
      run: |
          git config --global user.name "dothq-robot"
          git config --global user.email "72629236+dothq-robot@users.noreply.github.com"

    - name: Push to GitHub
      run: |
          git pull
          git status
          git add .
          git commit -m "🆙 Update demo"
          git push origin gh-pages
