name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - name: Build
      run: |
        yarn
        yarn build
        
    - name: Push
      uses: ad-m/github-push-action@v0.6.0
      with:
          branch: gh-pages
